language: node_js
node_js:
  - "6"
  - "5"

services:
  - postgresql
addons:
  postgresql: "9.6"

before_script:
  - echo "create database markov_test;" | psql -U postgres
  - cat sql/markov.sql | psql -U postgres markov_test

env:
  - PGUSER=postgres
  - PGHOST=/var/run/postgresql
  - PGDATABASE=markov_test
